### ISSUE TITLE
The class of EntropySGD

### ISSUE THREAD

**Issue by lyatdawn** [ucla-vision/entropy-sgd#1]
In python/optim.py, at line 71, you do this:
dw = w.grad.data
Is it implement the equation of 4:
The paper's Algorith 1.
If so, does dw = w.grad.data do the forward and backward of the network, and, how does it work? Can you explain this clearly?
Thanks!

**Comment by pratikac** [comment]
No, [line 68 in optim.py](https://github.com/ucla-vision/entropy-sgd/blob/master/python/optim.py#L68) implements the forward-backward prop. Please see the function [feval](https://github.com/ucla-vision/entropy-sgd/blob/master/python/train.py#L66-L79) in [train.py](https://github.com/ucla-vision/entropy-sgd/blob/master/python/train.py).

**Comment by lyatdawn** [comment]
Thanks very much. I will research it.
